Repository EventGhost/EventGhost, pull requests merged in 2018-10, with the labels that each got.

#283 Appicon selection
  _build/builder/BuildLibrary.py
  _build/data/InnoSetup.template
  _build/data/docs/_static/arrow.ico
  _build/data/docs/_static/ghost.ico
  _build/data/docs/_static/logo.png
  _build/data/docs/_static/logo_small.bmp
  _build/data/docs/_static/logo_small.png
  _build/data/docs/conf.py
Labels: enhancement

#317 Remove obsolete COMServer
  eg/Init.py
  eg/WinApi/COMServer.py
  eg/WinApi/GenPaths.py
Labels: change

#316 Makes EG more IDE compatible
  eg/__init__.py
Labels: enhancement, internal, new feature
