Repository EventGhost/EventGhost, pull requests merged in 2018-11, with the labels that each got.

#330 [PowerDVD] Update to work with newer PowerDVD versions (v12+)
  plugins/PowerDVD/__init__.py
Labels: enhancement

#323 Swaps out Named Pipe for Socket
  _build/builder/BuildDocs.py
  _build/builder/__init__.py
  _build/extensions/AES.pyd/AES.def
  _build/extensions/AES.pyd/AES.sln
  _build/extensions/AES.pyd/AES.vcxproj
  _build/extensions/AES.pyd/AES.vcxproj.filters
  _build/extensions/AES.pyd/AES.vcxproj.user
  _build/extensions/AES.pyd/crypt.cpp
  _build/extensions/AES.pyd/stdafx.cpp
  _build/extensions/AES.pyd/stdafx.h
  _build/extensions/AES.pyd/targetver.h
  _build/extensions/CryptoSocket.pyd/CryptoSocket.pyx
  eg/Classes/Document.py
  eg/Classes/MainFrame/__init__.py
  eg/Cli.py
  eg/Core.py
  eg/Init.py
  eg/LoopbackSocket.py
  eg/NamedPipe.py
  eg/__init__.py
  lib27/site-packages/AES.pyd
Labels: bugfix

#315 BuildLibrary.py: fix SyntaxError in py2exe for Jinja2
  .appveyor.yml
  _build/builder/BuildLibrary.py
  _build/builder/CheckDependencies.py
Labels: bugfix, internal

#326 Fix links to the EventGhost website in Readme
  README.md
Labels: bugfix, internal

#325 Fixes getting the default user language from the OS
  eg/Classes/App.py
  eg/Classes/Translation.py
  eg/Utils.py
Labels: bug, enhancement

#337 [SchedulGhost] fix setting the repeat intervall
  plugins/SchedulGhost/__init__.py
Labels: bugfix
