Repository EventGhost/EventGhost, pull requests merged in 2019-03, with the labels that each got.

#368 Add hotkey to clear logpanel (suggested by Snowbird)
  eg/Classes/MainFrame/__init__.py
Labels: enhancement

#373 setting locale when Windows has no LCID for user selected locale settings
  eg/Cli.py
Labels: bugfix

#367 ConfigPanel.py: Enables Apply button on first configure
  eg/Classes/ConfigDialog.py
  eg/Classes/ConfigPanel.py
  eg/Classes/PluginItem.py
Labels: bugfix

#363 Updates InnoSetup version to 5.6.1
  .appveyor.yml
Labels: enhancement, internal
