Repository EventGhost/EventGhost, pull requests merged in 2019-01, with the labels that each got.

#353 Fix right click on empty psace in log don't show context menu
  eg/Classes/MainFrame/LogCtrl.py
Labels: bugfix

#341 [VLC] add 64 bit support, fix play, volup and voldown
  plugins/VLC/__init__.py
Labels: enhancement

#355 [EventGhost] TriggerEvent: option to remove the 'Main' prefix
  plugins/EventGhost/__init__.py
Labels: bugfix, enhancement

#356 Fix issue when locale has no translation (OptionsDialog.py), and right to left bug on (SpinNumCtrl.py)
  eg/Classes/OptionsDialog.py
  eg/Classes/SpinNumCtrl.py
Labels: bugfix
